### ISSUE TITLE
Be able to see previous analysis when a new one is planned.

### ISSUE THREAD

**Issue by Etuldan** [aeris/cryptcheck#10]
On the website, when a new analysis is launch (in order to refresh the data), when the url is visited, it's only written : 

"
[HTTPS] Analyse en cours de xxxxxx
Début de l’analyse : xx/xx/xxxx xx:xx:xx
Merci de patienter… (Cette page se rafraîchit automatiquement toutes les 10 secondes)
"

It could be nice to be able to see the previous results (or maybe only the global "scores" ?), as the current analysis could take a while.

**Comment by aeris** [comment]
Must be open on aeris@cryptcheck-rails,
