### ISSUE TITLE
No more openssl-1.0.2d.tar.gz available on openssl.org

### ISSUE THREAD

**Issue by olivier-monaco** [aeris/cryptcheck#15]
I had to change OPENSSL_VERSION to 1.0.2e in Makefile.

**Comment by pfoo** [comment]
1.0.2d is still available, but the url has changed. See http://openssl.org/source/old/1.0.2/openssl-1.0.2d.tar.gz

**Comment by aeris** [comment]
Stable (at the time of the Makefile writing) OpenSSL release have not stable URL…
So difficult to make a fix Makefile and difficult to change it on each OpenSSL release :'(
