### ISSUE TITLE
Support cipher CHACHA20-POLY1305

### ISSUE THREAD

**Issue by HLFH** [aeris/cryptcheck#19]
Coucou @aeris ,

Ce serait super de supporter le cipher CHACHA20-POLY1305. Sur Arch, j'ai installé `nginx-mainline-libressl`. Et du coup, j'utilise que ECDHE-RSA-CHACHA20-POLY1305 et quand Let's Encrypt supportera ECDSA, ce ne sera que ECDHE-ECDSA-CHACHA20-POLY1305.

Et puis, la version 1.02g d'OpenSSL du 01/03/2016 supporte CHACHA20-POLY1305, [si j'ai bien lu](https://www.openssl.org/news/changelog.html#x1).

SSL Labs ne le supporte pas non plus pour l'instant. 

Merci,
T'es trop cool,
HLFH

**Comment by aeris** [comment]
N’utiliser que CHACHA20-POLY1305 me semble très… risqué, étant donné le peu de compatibilité des clients sur cette cipher. Firefox ne le supporte pas par exemple.
Si OpenSSL est compilé avec CHACHA-POLY, CryptCheck le supportera automatiquement :)

**Comment by HLFH** [comment]
Firefox n'est malheureusement plus la référence mais Chrome. J'aime bien les services autohébergés et j'utiliserai majoritairement ce cipher dessus.

Du coup, tu comptes mettre à jour OpenSSL à la version 1.02g pour que ton service https://tls.imirhil.fr/ le supporte ? Merci !

**Comment by aeris** [comment]
1.0.2g ne supporte pas encore CHACHA+POLY, c’est uniquement prévu pour la prochaine grosse release.
Et vu qu’il n’y a que Chrome à le supporter, c’est de toute façon une très mauvaise idée de n’activer que ça :D

**Comment by HLFH** [comment]
Oups effectivement j'ai mal lu. Je pensais qu'ils avaient avancé leur projet. C'est donc bien la 1.1.0. Chrome est le nouvel Internet Explorer. Il est tellement innovant ! Il supporte des trucs géniaux tandis que Firefox ne veut pas le supporter, genre [HTML Imports](https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports) ou [U2F](https://bugzilla.mozilla.org/show_bug.cgi?id=1065729).

**Comment by aeris** [comment]
Oui, et il track ta vie privée. Et c’est Google derrière. Etc.
Pas forcément une méga-bonne chose que ce navigateur devienne la référence…

**Comment by HLFH** [comment]
Je suis d'accord avec toi. Cela blesse les cœurs des libristes et hackers qui œuvrent pour les Communs. Je ne vois malheureusement  pas d'alternative immédiate à Chrome si Firefox ne reprend pas du galon dans les trois prochaines années.

**Comment by aeris** [comment]
Corrigé avec le commit 2c7ed5307e923705bf0e4f0142bf97e81a19816d

**Comment by HLFH** [comment]
@aeris Merci, tu seras toujours mon gourou préféré. <3
