### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by leonklingele** [aeris/cryptcheck#22]
Hi @aeris,

we already talked a bit about localization support on IRC.
Is there anything I can do to translate this project into English / German?
You mentioned that the current setup allows for easy localization, I do however have no clue about Ruby. 😉

**Comment by aeris** [comment]
Wrong project here to :P 
I worked on the web part today, and now the project is available for internationalisation with https://github.com/aeris/cryptcheck-rails/commit/5bce485c76ce83053cd66ee970e0709ba1189ac8
Here are the files for translation : https://github.com/aeris/cryptcheck-rails/blob/master/config/locales/en.yml
