### ISSUE TITLE
Blog post or reading materials?

### ISSUE THREAD

**Issue by jdalton** [aeris/cryptcheck#24]
Hi @aeris,

I'd like to learn more about how to improve my site's score. The summary of results is great but I'm wondering if there's additional reading with steps to take to improve things.

**Comment by aeris** [comment]
Hi !
There is a big blog post about TLS implementation and advices on configuration on [my blog](https://blog.imirhil.fr/2015/09/02/cryptcheck-verifiez-implementations-tls.html), but it’s in French :'(
Future version of cryptcheck will have a full page for explanation of errors (with translations !)

If you prefer more physical reading, I recommend you [OpenSSL Cookbook](https://www.feistyduck.com/books/openssl-cookbook/) from Ivan Ristić.

**Comment by jdalton** [comment]
Thank you!
