### ISSUE TITLE
Amélioration du design

### ISSUE THREAD

**Issue by theotix** [aeris/cryptcheck#31]
Bonjour,
Suite à [quelques tweets](https://twitter.com/aeris22/status/905010588820140032) j'ai cru comprendre que tu serais intéressé par une amélioration de l'interface du site (après avoir préféré faire utiliser une capture de SSLLabs plutôt CryptCheck).
Si c'est le cas, je veux bien me proposer pour commencer à réfléchir à une refonte (sachant que si ça se concrétise, je suis en capacité de m'occuper aussi de l'intégration en code)

J'aurais dans ce cas quelques questions pour diriger mes recherches :
- Qu'est-ce qu'il te dérange dans l'interface actuelle (ou des retours négatifs que tu as peu avoir dessus) ?
- Quelles sont les différentes fonctionnalités de l'outil, avec les informations à afficher pour chacune (n'étant pas spécialiste en crypto, je préfère demande les choses importantes à affiche, histoire d'avoir une hiérarchie du contenu pas trop bordélique)
- As-tu une idée des cas d'utilisations possibles de l'outil ? (quand, dans quel contexte, avec quel type d'appareil CryptCheck serait utilisé). Histoire de pouvoir améliorer l'expérience proposée.

Voili voilou, si je peux aider. (dans les limites du stock de temps et d'énergie disponible)

**Comment by aeris** [comment]
Hello !

Alors l’interface actuelle est bien, c’est juste avec la v2 qu’elle commence à montrer ses limites.
Il y a **beaucoup** plus d’information à afficher sur un même écran, et ça donne un résultat pitoyable quand c’est moi qui m’en occupe, vu que je suis développeur et pas designer :P

L’ensemble des infos à afficher pour la v2 est visible ici :
https://github.com/aeris/cryptcheck-rails/blob/need-html/config/host.yml
