### ISSUE TITLE
mettre une petite légende en face des protocoles

### ISSUE THREAD

**Issue by Grummfy** [aeris/cryptcheck#33]
Salut,
je pense que cela serait pas mal de mettre un title ou une légende sur chacune des couleurs. Cela permettrait de rendre la chose plus clair...

Bonne journée

**Comment by aeris** [comment]
Concerne plutôt https://github.com/aeris/cryptcheck-rails
La documentation est en cours d’écriture : https://cryptcheck.fr/help

**Comment by Grummfy** [comment]
merci
