### ISSUE TITLE
Pimp my UX

### ISSUE THREAD

**Issue by BillCarsonFr** [aeris/cryptcheck#35]
Help request by aeris to enhance current UI.
I see here two options:
- Stay with Tables: As always table can have an out-dated look and feel. But some work can be put here to give it a more modern look and feel (Typical 'less is more' approach, less borders, less bold, fix some alignment inconsistencies). Not easy though, there is lots of data.

- Change for other layout (maybe cards?). There are several redundancies  with current display of data, the name of the suite gave a lot on the handshake/cryptography/integrity alg used. Opportunity for alternative layout? This layout could also be more suitable for responsive adaptation.

I can propose quick overview for both options, but if you have a preference please let me know.

**Comment by aeris** [comment]
UI issue is to open [here](https://github.com/aeris/cryptcheck-rails/issues) 😄
