### ISSUE TITLE
docker image for the new-scoring branch ?

### ISSUE THREAD

**Issue by dalf** [aeris/cryptcheck#47]
Currently https://hub.docker.com/r/aeris22/cryptcheck:latest is built using the master branch.

Is there a docker image built using the new-scoring branch ?

**Comment by aeris** [comment]
Currently not, but I can build one :)

**Comment by dalf** [comment]
If it is possible yes.

Side note: the purpose is to be able to build the docker image for https://github.com/dalf/cryptcheck-backend which is basically made of [one script](https://github.com/dalf/cryptcheck-backend/blob/master/cryptcheck-backend)

**Comment by aeris** [comment]
Hum, after review, the only version on the hub is this `new-scoring` v2 branch :thinking:

**Comment by aeris** [comment]
I push a new version with latest modifications !

**Comment by dalf** [comment]
Thank you !

**Comment by dalf** [comment]
Is it possible to update the docker image ?

**Comment by aeris** [comment]
Done.
I will create a CI/CD to automate this :blush:
