### ISSUE TITLE
undefined method 'ecda?' for nil:NilClass

### ISSUE THREAD

**Issue by gorinje** [aeris/cryptcheck#55]
Hi,

On some websites, I get this message :
undefined method 'ecda?' for nil:NilClass

For example, _cryptcheck https 20minutes.fr_

I'm using the latest version of the master that runs on Ubuntu 21.04 with ruby 2.7.2p13.

Should I downgrade the ruby version?

Many thanks

**Comment by aeris** [comment]
Hello!

As mentioned in the README, CryptCheck relies on very old, deprecated and unsecured custom patched versions for Ruby (2.2/2.3) and OpenSSL (1.0.2j) to support low level TLS access and old cipher suite needed for scoring.

It's not possible to use 2.4+ ruby, and not recommended to use CryptCheck outside a throwable virtual machine. Installation process is quite complicated and use many tricks clearly not compatible with production or daily used machine :sweat_smile: 

I advice you to use instead pre-built docker image embedding all this process: `docker run --rm aeris22/cryptcheck https`
It's also compatible with batch scripting with a JSON output : `docker run --rm aeris22/cryptcheck https 20minutes.fr -jq`

**Comment by gorinje** [comment]
That's perfect, many thanks!
