### ISSUE TITLE
Error during analysis: sslv3 alert handshake failure

### ISSUE THREAD

**Issue by extremelyonline** [aeris/cryptcheck#60]
Hi, when I tried to do a Cryptcheck on [my website](https://cryptcheck.fr/https/opnxng.com), it seems that Cryptcheck cannot reach. (Other sites such as [this one](https://tls.imirhil.fr/https/opnxng.com) work.)

The error is as follows. May I please ask what does this mean?  Is this problem related to my cipher sets? Thank you.

`Error during analysis: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure`

**Comment by aeris** [comment]
Hello

Don't know what is your TLS config, but seems [SSLLabs](https://www.ssllabs.com/ssltest/analyze.html?d=opnxng.com&s=202.182.109.92) struggle to analyse your site too, and OpenSSL just hang too : 

```
$ openssl s_client -connect opnxng.com:443
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 316 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

**Comment by extremelyonline** [comment]
I am not sure if this is the root cause, but the problem went away after I fixed the ciphers. Thanks!
