### ISSUE TITLE
Lower score on subdomain

### ISSUE THREAD

**Issue by mkody** [aeris/cryptcheck#61]
Hi,

With cryptcheck.fr I got [an E rank on `search.im-in.space`](https://cryptcheck.fr/https/search.im-in.space) and while I would take that as I need to fix my settings I can't really understand what and how when the same server and TLS config gives me [an A+ for `im-in.space`](https://cryptcheck.fr/https/im-in.space).
Trying again but on [tls.imirhil.fr](https://tls.imirhil.fr/https/search.im-in.space) I get an A.

Is there something not working properly with it being a subdomain? Or am I missing something?
Thanks.

**Comment by aeris** [comment]
Hello!

Seems you haven't HSTS enable on this website, and so the `E` rank.

It's visible on the JSON raw result
https://cryptcheck.fr/https/search.im-in.space.json

**Comment by mkody** [comment]
Oh, thanks for the JSON raw results, that's useful!

I now found the cause - server may be returning a non-200 code so nginx wasn't adding the header without `always`. Thanks!
